### PR TITLE
FIX: Composer is already loaded

### LINKED ISSUE #16: AWS Client return error MissingEndTime
Get the error from AWS client.
Do you have any idea about my error message? 

AWS Client return error
`"UnprocessedTraceSegments": [
        {
            "Id": "c2a0319811ccbc58",
            "ErrorCode": "MissingEndTime",
            "Message": "Invalid subsegment. ErrorCode: MissingEndTime, Cause: null"
        }
    ],
    "@metadata": {
        "statusCode": 200,
        "effectiveUri": "https:\/\/xray.ap-east-1.amazonaws.com\/TraceSegments",
        "headers": {
            "date": "Sat, 15 May 2021 10:56:22 GMT",
            "content-type": "application\/json",
            "content-length": "156",
            "connection": "keep-alive",
            "x-amzn-requestid": "022d118f-b269-448c-b895-ae8e195d8962"
        },
        "transferStats": {
            "http": [
                []
            ]
        }
    }`

Submit data
`{
  "id": "c2a0319811ccbc58",
  "trace_id": "1-609fa8d4-1fad76e1dd7f69f43beb0695",
  "name": "***",
  "start_time": 1621076180.124956,
  "end_time": 1621076181.859172,
  "subsegments": [...]
    }
  ],
  "annotations": {
    "Framework": "Laravel 5.8.38",
    "PHP Version": "7.4.2"
  },
  "http": {
    "request": {
      "url": "***",
      "method": "GET",
      "client_ip": "::1"
    },
    "response": {
      "status": 200
    }
  }
}`

### PR DESCRIPTION
**Pull request by kimegede**
`$this->app->booting()` wasn't called at all.

Fixes #16

### CODE REVIEW

**Comment by kimegede** [comment]
Testing this.

**Comment by Odder** [comment]
Explanation:
It seems that `$this->app->booting()` is being reached AFTER Laravel starts booting but before it has finished booting, thus the `booting()` callback registered will never be called and we will not be be able to programmatically confirm whether or not the application has started booting (as the Laravel only keeps track of `isBooted()` and not something like `isBooting`)!

This hotfix will make the assumption that by the time we reach `$this->app->booting()` we must have started booting the application.

**Comment by kimegede** [comment]
That seem to fix it - @viezel.
Can you please review if you are happy with this change?

**Comment by viezel** [comment]
Thanks 👍🏻

**Pull request merged**
